services:
  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: development
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./backend
      target: development
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  uploads_data: